### ISSUE TITLE
Open filenames without specifying the suffix or compression type

### ISSUE THREAD

**Issue by chris8754** [pycompression/xopen#134]
A request that files could be opened without specifying the compression suffix or compression type. For example instead of saying
xopen("filename.gz")
use
xopen("filename")
in this use case, xopen would search for "filename", "filename.gz", "filename.bz2", "filename.zst", etc. It would throw an exception if multiple matches occur.
This allows user's code to be more maintainable and independent of the compression method. In my specific case we are slowly transitioning from gzip to zstandard, and this is hampered by the numerous scripts and programs that explicitly open .gz files.
Thank you

**Comment by rhpvorderman** [comment]
`xopen("filename")` currently opens a file named `filename`. Doing anything else would lead to lots of surprising results. 

xopen is already able to determine the compression method from the file header, so strictly speaking, it does need a file with an extension.

**Comment by marcelm** [comment]
As @rhpvorderman said, it would be too suprising to change the semantics for `xopen()` itself.

This should probably be implemented as a separate function that uses `xopen()`. I am not sure at the moment whether we would accept a PR adding such a function, but that’s where you could start. An actual implementation could also help in clarifying the details. For example, I assume this would only be used for *reading* files because when writing, the compression format needs to be specified somehow anyway.

**Comment by chris8754** [comment]
Yes, perhaps it should be a separate function. Expected behavior could differ per use case, like what to do if multiple extensions exist with same basename. Trying to open "filename" when "filename.xz" and "filename.zst" exist in the same directory. Different behavior is possible.
I'll close this. Thank you.
