### ISSUE TITLE
zip support

### ISSUE THREAD

**Issue by jayvdb** [pycompression/xopen#27]
Is it ok to add other compression formats?
It is curious that zip is missing when it is part of the stdlib.

**Comment by rhpvorderman** [comment]
Of course that is okay. Feel free to make a PR!

Zip is missing because zip is not a format for a compressed file. Zip is a format for a container of (optionally compressed) files. A `.zip` may contain multiple files while `.gz`, `.bzip2` and `.xz` only contain one file. Also a `.zip` may be empty. Xopen works filestreams and can only work with file formats that contain exactly one file. Since a zip file can contain zero or more than one file it is unsuitable. 

The stdlib implementation of zip handles this container aspect well and with an intuitive interface.

**Comment by rhpvorderman** [comment]
Closing this issue. Container formats will never be supported as explained above.

For people who want to work with zip and tar files, please have a look at the standard library. Python has some builtin modules that handle this problem:

- Zip files: https://docs.python.org/3/library/zipfile.html
- Tar files: https://docs.python.org/3/library/tarfile.html

I have worked with the `zipfile` module myself and it is very good. Intuitive and easy to use.
