### ISSUE TITLE
Support ZIP files

### ISSUE THREAD

**Issue by eli-osherovich** [pycompression/xopen#69]
Another popular archive format....

**Comment by marcelm** [comment]
This has been requested in #27 already. Please see the discussion over there. As described, zip files are containers, which xopen doesn’t focus on. What’s your use case?

It may possibly be interesting to support zip archives that contain exactly one file, but then I’d like to know an example where that would actually be helpful.

**Comment by eli-osherovich** [comment]
Thanks, @marcelm .
My suggestion is to add an additional parameter (say, `name`)  to `xopen()` to let it open that particular file in a container.

**Comment by rhpvorderman** [comment]
The use case for xopen is that users may have `.xz`, `.bz2`, `.gz` or non-compressed files that they'd like to open and you as a developer don't know beforehand which compression (or no compression) they will use. xopen handles that hassle.

If you **do know** beforehand which format is used, it is much faster and clearer to use a Python stdlib interface to said format. (Unless it is gzip, because we performance-optimised the hell out of it). 

Is there  a reason why [zipfile](https://docs.python.org/3/library/zipfile.html) does not handle your particular use case?

**Comment by eli-osherovich** [comment]
I have different compressions (gz, zip, etc.) and I want to use one api to open them all.

**Comment by rhpvorderman** [comment]
As I stated before gz and zip are not comparable. gz is a compressed **filestream**. zip is a **data container** that can contain 0 or multiple files. These files may in the case of zip even be compressed with different algorithms. 

Xopen was written to handle filestreams only. Specifically, in the speediest matter possible. There is no container-aware code whatsoever in the current API. It is not in the project scope. The whole architecture is simply not build for containers.

It would be much easier to write a completely new library. One that is specifically made for containers. That library could support zip, tar, 7zip etc. It could also support gz, xz, etc as containers which only contain one file (but that is not a problem as tar zip etc. can at times also contain only one file). This new library could design an API that would make it easy and intuitive to unpack different container formats. The current xopen API will never be able to do that without transforming into a different project, in which case it is better to start a different project.

**Comment by eli-osherovich** [comment]
Never mind.
